In [1]:
from ultralytics import YOLO

# Load model YOLOv8 pre-trained
model = YOLO("C:/SEMESTER 5/PCD (Image Processing)/Plat Nomor2/yolov8n.pt")  # Model dasar

# Train model dengan dataset plat nomor
model.train(
    data="C:/SEMESTER 5/PCD (Image Processing)/Plat Nomor2/data.yaml",   # Path ke file data.yaml
    epochs=50,          # Jumlah epoch untuk pelatihan
    imgsz=640           # Ukuran gambar
)


New https://pypi.org/project/ultralytics/8.3.38 available  Update with 'pip install -U ultralytics'
Ultralytics 8.3.34  Python-3.11.0 torch-2.5.1+cpu CPU (Intel Core(TM) Ultra 7 155H)
engine\trainer: task=detect, mode=train, model=C:/SEMESTER 5/PCD (Image Processing)/Plat Nomor2/yolov8n.pt, data=C:/SEMESTER 5/PCD (Image Processing)/Plat Nomor2/data.yaml, epochs=50, time=None, patience=100, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=train, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic

train: Scanning C:\SEMESTER 5\PCD (Image Processing)\Plat Nomor2\train\labels... 70 images, 0 backgrounds, 0 corrupt: 100%|██████████| 70/70 [00:00<00:00, 1301.67it/s]

train: New cache created: C:\SEMESTER 5\PCD (Image Processing)\Plat Nomor2\train\labels.cache



INFO:albumentations.check_version:A new version of Albumentations is available: 1.4.21 (you have 1.4.10). Upgrade using: pip install --upgrade albumentations


albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))


val: Scanning C:\SEMESTER 5\PCD (Image Processing)\Plat Nomor2\valid\labels... 19 images, 0 backgrounds, 0 corrupt: 100%|██████████| 19/19 [00:00<00:00, 1734.13it/s]

val: New cache created: C:\SEMESTER 5\PCD (Image Processing)\Plat Nomor2\valid\labels.cache


Plotting labels to runs\detect\train\labels.jpg... 
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically... 
optimizer: AdamW(lr=0.001, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 0 dataloader workers
Logging results to runs\detect\train
Starting training for 50 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       1/50         0G      1.663      4.097      1.397        103        640: 100%|██████████| 5/5 [00:13<00:00,  2.75s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:02<00:00,  2.44s/it]

                   all         19        138     0.0176       0.65      0.272      0.184



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       2/50         0G       1.64       3.87      1.312        103        640: 100%|██████████| 5/5 [00:13<00:00,  2.65s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.08s/it]

                   all         19        138     0.0215       0.76      0.271      0.154



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       3/50         0G      1.603      3.304      1.235        114        640: 100%|██████████| 5/5 [00:13<00:00,  2.63s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00,  1.04it/s]

                   all         19        138     0.0185      0.784      0.295      0.155



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       4/50         0G       1.52      2.562      1.211         65        640: 100%|██████████| 5/5 [00:13<00:00,  2.67s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.16s/it]

                   all         19        138     0.0186      0.792      0.298      0.151



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       5/50         0G      1.544      1.987      1.217        131        640: 100%|██████████| 5/5 [02:06<00:00, 25.33s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:08<00:00,  8.95s/it]

                   all         19        138      0.993      0.136      0.284      0.145



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       6/50         0G      1.497      1.797      1.211        108        640: 100%|██████████| 5/5 [01:14<00:00, 14.91s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.03s/it]

                   all         19        138      0.984      0.161      0.284       0.14



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       7/50         0G      1.541      1.679      1.204         88        640: 100%|██████████| 5/5 [00:12<00:00,  2.57s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00,  1.04it/s]

                   all         19        138      0.994      0.186      0.321      0.177



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       8/50         0G      1.507      1.522      1.152         87        640: 100%|██████████| 5/5 [00:13<00:00,  2.68s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00,  1.00it/s]

                   all         19        138       0.99      0.206       0.35      0.212



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


       9/50         0G      1.487      1.424      1.152         82        640: 100%|██████████| 5/5 [00:13<00:00,  2.65s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00,  1.03it/s]

                   all         19        138      0.977      0.232      0.377      0.204



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      10/50         0G      1.537      1.399      1.152        111        640: 100%|██████████| 5/5 [00:13<00:00,  2.68s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.16s/it]

                   all         19        138      0.978      0.244      0.383      0.221



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      11/50         0G      1.495      1.334      1.128        124        640: 100%|██████████| 5/5 [00:13<00:00,  2.68s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.06s/it]

                   all         19        138      0.956      0.249      0.409      0.239



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      12/50         0G      1.483      1.312      1.123         87        640: 100%|██████████| 5/5 [00:14<00:00,  2.83s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.15s/it]

                   all         19        138      0.768      0.297      0.443      0.259



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      13/50         0G      1.423      1.337      1.094         78        640: 100%|██████████| 5/5 [00:12<00:00,  2.53s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.06s/it]

                   all         19        138      0.764      0.319      0.453      0.263



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      14/50         0G      1.416      1.233      1.101         79        640: 100%|██████████| 5/5 [00:13<00:00,  2.65s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.04s/it]

                   all         19        138      0.746      0.309      0.458      0.262



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      15/50         0G       1.42      1.222      1.082        110        640: 100%|██████████| 5/5 [00:13<00:00,  2.75s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.08s/it]

                   all         19        138       0.59      0.411      0.483      0.274



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      16/50         0G      1.404       1.25      1.099         85        640: 100%|██████████| 5/5 [00:14<00:00,  2.80s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.04s/it]

                   all         19        138      0.621      0.453       0.51      0.293



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      17/50         0G      1.347      1.148      1.048        134        640: 100%|██████████| 5/5 [00:13<00:00,  2.76s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.14s/it]

                   all         19        138      0.627      0.468      0.557      0.338



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      18/50         0G      1.398      1.147      1.071        162        640: 100%|██████████| 5/5 [00:14<00:00,  2.81s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.16s/it]

                   all         19        138      0.579       0.43      0.573      0.337



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      19/50         0G      1.357      1.181       1.07         70        640: 100%|██████████| 5/5 [00:14<00:00,  2.81s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.05s/it]

                   all         19        138      0.571      0.432      0.567       0.33



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      20/50         0G      1.363      1.141      1.064         93        640: 100%|██████████| 5/5 [00:13<00:00,  2.69s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.16s/it]

                   all         19        138      0.799      0.404      0.584      0.355



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      21/50         0G      1.375      1.211      1.075         72        640: 100%|██████████| 5/5 [00:13<00:00,  2.66s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.10s/it]

                   all         19        138      0.661      0.478      0.625      0.388



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      22/50         0G      1.376      1.159      1.022         88        640: 100%|██████████| 5/5 [00:13<00:00,  2.71s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.03s/it]

                   all         19        138      0.706      0.626      0.663      0.409



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      23/50         0G      1.314      1.167      1.023         66        640: 100%|██████████| 5/5 [00:13<00:00,  2.70s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.20s/it]

                   all         19        138       0.68      0.752       0.65      0.389



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      24/50         0G      1.312      1.077      1.039         89        640: 100%|██████████| 5/5 [00:13<00:00,  2.69s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.19s/it]

                   all         19        138       0.66      0.791      0.675      0.381



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      25/50         0G      1.308      1.057      1.033         82        640: 100%|██████████| 5/5 [00:14<00:00,  2.86s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.28s/it]

                   all         19        138       0.64      0.826      0.653      0.377



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      26/50         0G      1.372      1.073       1.05         90        640: 100%|██████████| 5/5 [00:13<00:00,  2.76s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.10s/it]

                   all         19        138      0.645      0.782      0.661      0.385



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      27/50         0G       1.33     0.9954      1.041         94        640: 100%|██████████| 5/5 [00:14<00:00,  2.80s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.29s/it]

                   all         19        138       0.67      0.773      0.791      0.476



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      28/50         0G      1.327      1.011      1.049         82        640: 100%|██████████| 5/5 [00:13<00:00,  2.80s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.19s/it]

                   all         19        138      0.685      0.713      0.783      0.491



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      29/50         0G      1.281      1.007      1.025         65        640: 100%|██████████| 5/5 [00:14<00:00,  2.85s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.21s/it]

                   all         19        138      0.655      0.712      0.779      0.483



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      30/50         0G      1.336      1.027      1.048         75        640: 100%|██████████| 5/5 [00:13<00:00,  2.77s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.13s/it]

                   all         19        138      0.665      0.722       0.78      0.489



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      31/50         0G      1.279     0.9814      1.023        113        640: 100%|██████████| 5/5 [00:14<00:00,  2.89s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.06s/it]

                   all         19        138      0.673      0.725      0.782      0.489



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      32/50         0G      1.301     0.9519      1.019         78        640: 100%|██████████| 5/5 [00:13<00:00,  2.69s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.14s/it]

                   all         19        138      0.616      0.735      0.797      0.475



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      33/50         0G      1.301     0.9955      1.013        112        640: 100%|██████████| 5/5 [00:14<00:00,  2.83s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.26s/it]

                   all         19        138      0.637      0.737      0.798      0.481



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      34/50         0G      1.244     0.9283          1        139        640: 100%|██████████| 5/5 [00:14<00:00,  2.89s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.18s/it]

                   all         19        138      0.623      0.734      0.797      0.481



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      35/50         0G      1.231     0.9638     0.9853         92        640: 100%|██████████| 5/5 [00:14<00:00,  2.81s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.24s/it]

                   all         19        138      0.657      0.754      0.801      0.493



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      36/50         0G      1.225     0.8974       1.01         84        640: 100%|██████████| 5/5 [00:13<00:00,  2.78s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.20s/it]

                   all         19        138      0.832      0.759      0.834      0.524



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      37/50         0G      1.215     0.9168     0.9913         87        640: 100%|██████████| 5/5 [00:13<00:00,  2.65s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.08s/it]

                   all         19        138      0.831      0.748      0.832       0.52



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      38/50         0G      1.199     0.9051     0.9931         91        640: 100%|██████████| 5/5 [00:13<00:00,  2.76s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.15s/it]

                   all         19        138      0.876      0.721      0.829      0.496



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      39/50         0G      1.202      0.885     0.9864         72        640: 100%|██████████| 5/5 [00:13<00:00,  2.72s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.09s/it]

                   all         19        138      0.905      0.715      0.828      0.496



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      40/50         0G      1.213     0.9039     0.9951         71        640: 100%|██████████| 5/5 [00:13<00:00,  2.76s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.14s/it]

                   all         19        138      0.747      0.773      0.812      0.485


Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      41/50         0G      1.198      1.028     0.9822         43        640: 100%|██████████| 5/5 [00:14<00:00,  2.82s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.10s/it]

                   all         19        138       0.78      0.765      0.812      0.481



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      42/50         0G      1.236     0.9958     0.9827         62        640: 100%|██████████| 5/5 [00:13<00:00,  2.71s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.22s/it]

                   all         19        138       0.77      0.809      0.822      0.489



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      43/50         0G       1.22      1.003     0.9684         52        640: 100%|██████████| 5/5 [00:12<00:00,  2.56s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.26s/it]

                   all         19        138      0.782      0.836       0.85      0.534



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      44/50         0G       1.15     0.9422     0.9661         32        640: 100%|██████████| 5/5 [00:13<00:00,  2.62s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.10s/it]

                   all         19        138       0.85      0.809      0.856      0.554



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      45/50         0G      1.237     0.9503      1.003         34        640: 100%|██████████| 5/5 [00:12<00:00,  2.59s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.41s/it]

                   all         19        138      0.854      0.815      0.862      0.556



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      46/50         0G      1.215     0.9432     0.9657         51        640: 100%|██████████| 5/5 [00:13<00:00,  2.65s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.20s/it]

                   all         19        138      0.857      0.833      0.869      0.556



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      47/50         0G      1.187     0.9295     0.9581         66        640: 100%|██████████| 5/5 [00:18<00:00,  3.67s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:08<00:00,  8.26s/it]


                   all         19        138      0.827      0.851      0.876      0.532

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      48/50         0G      1.145      0.914     0.9563         41        640: 100%|██████████| 5/5 [00:40<00:00,  8.19s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:00<00:00,  1.06it/s]

                   all         19        138      0.778      0.856      0.873      0.523



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      49/50         0G      1.151     0.8966     0.9579         35        640: 100%|██████████| 5/5 [00:12<00:00,  2.44s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.09s/it]

                   all         19        138      0.792      0.856      0.877      0.527



      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size


      50/50         0G      1.183     0.9127     0.9646         57        640: 100%|██████████| 5/5 [00:12<00:00,  2.52s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.21s/it]

                   all         19        138      0.803      0.856      0.878      0.526



50 epochs completed in 0.274 hours.
Optimizer stripped from runs\detect\train\weights\last.pt, 6.2MB
Optimizer stripped from runs\detect\train\weights\best.pt, 6.2MB

Validating runs\detect\train\weights\best.pt...
Ultralytics 8.3.34  Python-3.11.0 torch-2.5.1+cpu CPU (Intel Core(TM) Ultra 7 155H)
Model summary (fused): 168 layers, 3,006,818 parameters, 0 gradients, 8.1 GFLOPs


                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:01<00:00,  1.09s/it]


                   all         19        138      0.856      0.834      0.869      0.555
                 Bajaj          1          1      0.852          1      0.995      0.796
                 Mobil         12         20      0.853        0.9      0.933      0.714
                 Motor         16         49      0.883      0.918      0.922      0.411
                  Truk          4          4      0.828       0.75      0.777       0.59
                  plat         19         64      0.865      0.599       0.72      0.263
Speed: 0.6ms preprocess, 33.2ms inference, 0.0ms loss, 3.0ms postprocess per image
Results saved to runs\detect\train


ultralytics.utils.metrics.DetMetrics object with attributes:

ap_class_index: array([0, 2, 3, 4, 5])
box: ultralytics.utils.metrics.Metric object
confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x000001D7324BC390>
curves: ['Precision-Recall(B)', 'F1-Confidence(B)', 'Precision-Confidence(B)', 'Recall-Confidence(B)']
curves_results: [[array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
    

In [2]:
from ultralytics import YOLO
model = YOLO("C:/SEMESTER 5/PCD (Image Processing)/Plat Nomor2/runs/detect/train/weights/best.pt")
results = model('C:/SEMESTER 5/PCD (Image Processing)/Plat Nomor2/test/images/0_IDN_220113012101_20240619083857296_X944Y328W35H12_Motorcycle_Audi_unknown_057_03_09745_jpg.rf.1b4b7ea93d080337cfb58eeb73f67e73.jpg')
xyxy = results[0].boxes.xyxy.cpu().numpy()

print(xyxy)


image 1/1 C:\SEMESTER 5\PCD (Image Processing)\Plat Nomor2\test\images\0_IDN_220113012101_20240619083857296_X944Y328W35H12_Motorcycle_Audi_unknown_057_03_09745_jpg.rf.1b4b7ea93d080337cfb58eeb73f67e73.jpg: 384x640 1 Mobil, 5 Motors, 3 plats, 79.7ms
Speed: 5.2ms preprocess, 79.7ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)
[[     353.17      24.144      574.01      331.62]
 [     755.72       422.8      809.17      444.98]
 [     738.37      390.79      828.56      559.38]
 [     885.51      102.13      949.92      220.37]
 [     415.98      291.43      478.03      316.73]
 [     905.92      301.08      1007.3      456.92]
 [     750.18        1.55      812.23      104.09]
 [     1052.3      1.7369      1109.7      84.049]
 [     943.22      333.91      983.49      351.43]]


## Membuat Box untuk Plat Nomer dan Kendaraan

In [7]:
import os
import cv2
from ultralytics import YOLO

# Load model YOLO
model = YOLO("C:/SEMESTER 5/PCD (Image Processing)/Plat Nomor2/runs/detect/train/weights/best.pt")

# Path folder input dan output
input_folder = "C:/SEMESTER 5/PCD (Image Processing)/Plat Nomor2/valid/images"
output_folder = "C:/SEMESTER 5/PCD (Image Processing)/Plat Nomor2/valid/results"

# Pastikan folder output ada
os.makedirs(output_folder, exist_ok=True)

# Nama kelas sesuai data.yaml
class_names = ['Bajaj', 'Bus', 'Mobil', 'Motor', 'Truk', 'Plat']

# Iterasi setiap file dalam folder input
for filename in os.listdir(input_folder):
    if filename.endswith(".jpg") or filename.endswith(".png"):  # Tambahkan format gambar lain jika perlu
        try:
            image_path = os.path.join(input_folder, filename)
            image = cv2.imread(image_path)

            if image is None:
                raise ValueError(f"Gambar {filename} tidak dapat dimuat.")

            # Inference dengan YOLO
            results = model(image_path)
            xyxy = results[0].boxes.xyxy.cpu().numpy()  # Koordinat bounding box
            conf = results[0].boxes.conf.cpu().numpy()  # Confidence score
            cls = results[0].boxes.cls.cpu().numpy()    # Class indices

            # Gambar bounding box pada gambar
            for box, confidence, class_id in zip(xyxy, conf, cls):
                x_min, y_min, x_max, y_max = map(int, box)  # Konversi ke integer
                label = f"{class_names[int(class_id)]}: {confidence:.2f}"  # Gunakan nama kelas dari data.yaml
                # Gambar kotak
                cv2.rectangle(image, (x_min, y_min), (x_max, y_max), (0, 255, 0), 2)
                # Tambahkan teks label
                cv2.putText(image, label, (x_min, y_min - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)

            # Simpan gambar hasil ke folder output
            output_path = os.path.join(output_folder, filename)
            cv2.imwrite(output_path, image)

            print(f"Hasil deteksi disimpan di: {output_path}")
        
        except Exception as e:
            print(f"Terjadi error pada file {filename}: {e}")



image 1/1 C:\SEMESTER 5\PCD (Image Processing)\Plat Nomor2\valid\images\0_AUS_220113012101_20240619180311560_X483Y537W29H11_Motorcycle_Audi_unknown_074_02_04640_jpg.rf.a4b60458d0903334af86eb182d28f0db.jpg: 384x640 2 Motors, 3 plats, 57.0ms
Speed: 1.0ms preprocess, 57.0ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)
Hasil deteksi disimpan di: C:/SEMESTER 5/PCD (Image Processing)/Plat Nomor2/valid/results\0_AUS_220113012101_20240619180311560_X483Y537W29H11_Motorcycle_Audi_unknown_074_02_04640_jpg.rf.a4b60458d0903334af86eb182d28f0db.jpg

image 1/1 C:\SEMESTER 5\PCD (Image Processing)\Plat Nomor2\valid\images\119005_IDN_220113012101_20240619135620295_X744Y537W72H20_SUV_MPV_Honda_white_066_02_01767_jpg.rf.c007cbedfd35a749cdd6608524c7c11f.jpg: 384x640 2 Mobils, 7 Motors, 6 plats, 50.9ms
Speed: 2.0ms preprocess, 50.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)
Hasil deteksi disimpan di: C:/SEMESTER 5/PCD (Image Processing)/Plat Nomor2/valid/results\

### Crop Objek yang telah terdeteksi

In [1]:
import os
import cv2
from ultralytics import YOLO

# Load model YOLO
model = YOLO("C:/SEMESTER 5/PCD (Image Processing)/Plat Nomor2/runs/detect/train/weights/best.pt")

# Path folder input, output, dan crop
input_folder = "C:/SEMESTER 5/PCD (Image Processing)/Plat Nomor2/train/images"
output_folder = "C:/SEMESTER 5/PCD (Image Processing)/Plat Nomor2/train/results"
crop_folder = "C:/SEMESTER 5/PCD (Image Processing)/Plat Nomor2/train/crops"

# Pastikan folder output dan crop ada
os.makedirs(output_folder, exist_ok=True)
os.makedirs(crop_folder, exist_ok=True)

# Nama kelas sesuai data.yaml
class_names = ['Bajaj', 'Bus', 'Mobil', 'Motor', 'Truk', 'Plat']

# Iterasi setiap file dalam folder input
for filename in os.listdir(input_folder):
    if filename.endswith(".jpg") or filename.endswith(".png"):  # Tambahkan format gambar lain jika perlu
        try:
            image_path = os.path.join(input_folder, filename)
            image = cv2.imread(image_path)

            if image is None:
                raise ValueError(f"Gambar {filename} tidak dapat dimuat.")

            # Inference dengan YOLO
            results = model(image_path)
            xyxy = results[0].boxes.xyxy.cpu().numpy()  # Koordinat bounding box
            conf = results[0].boxes.conf.cpu().numpy()  # Confidence score
            cls = results[0].boxes.cls.cpu().numpy()    # Class indices

            # Gambar bounding box pada gambar dan crop objek
            for idx, (box, confidence, class_id) in enumerate(zip(xyxy, conf, cls)):
                x_min, y_min, x_max, y_max = map(int, box)  # Konversi ke integer
                label = f"{class_names[int(class_id)]}: {confidence:.2f}"  # Gunakan nama kelas dari data.yaml

                # Gambar kotak
                cv2.rectangle(image, (x_min, y_min), (x_max, y_max), (0, 255, 0), 2)
                # Tambahkan teks label
                cv2.putText(image, label, (x_min, y_min - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)

                # Crop objek dari gambar asli
                cropped_object = image[y_min:y_max, x_min:x_max]

                # Simpan hasil crop ke folder crop
                crop_filename = f"{os.path.splitext(filename)[0]}_crop_{idx}.jpg"
                crop_path = os.path.join(crop_folder, crop_filename)
                cv2.imwrite(crop_path, cropped_object)

            # Simpan gambar hasil ke folder output
            output_path = os.path.join(output_folder, filename)
            cv2.imwrite(output_path, image)

            print(f"Hasil deteksi disimpan di: {output_path}")
            print(f"Cropping objek disimpan di folder: {crop_folder}")
        
        except Exception as e:
            print(f"Terjadi error pada file {filename}: {e}")



image 1/1 C:\SEMESTER 5\PCD (Image Processing)\Plat Nomor2\train\images\012TFN_IDN_220113012101_20240619135349974_X921Y521W33H13_Motorcycle_Audi_unknown_058_03_01252_jpg.rf.3de122885fc46aee03d3e5c69f400f84.jpg: 384x640 1 Mobil, 4 Motors, 1 plat, 165.2ms
Speed: 14.0ms preprocess, 165.2ms inference, 6.0ms postprocess per image at shape (1, 3, 384, 640)
Hasil deteksi disimpan di: C:/SEMESTER 5/PCD (Image Processing)/Plat Nomor2/train/results\012TFN_IDN_220113012101_20240619135349974_X921Y521W33H13_Motorcycle_Audi_unknown_058_03_01252_jpg.rf.3de122885fc46aee03d3e5c69f400f84.jpg
Cropping objek disimpan di folder: C:/SEMESTER 5/PCD (Image Processing)/Plat Nomor2/train/crops

image 1/1 C:\SEMESTER 5\PCD (Image Processing)\Plat Nomor2\train\images\0UPW_AUS_220313032101_20240619094952243_X1025Y610W42H16_Motorcycle_Audi_unknown_072_02_03288_jpg.rf.bc1d46be561a781b3ea737e40c450092.jpg: 384x640 2 Motors, 2 plats, 69.1ms
Speed: 3.0ms preprocess, 69.1ms inference, 1.0ms postprocess per image at sha

### Masukkan ke Excel

In [ ]:
import os
import cv2
import pandas as pd
from ultralytics import YOLO

# Load model YOLO
model = YOLO("C:/SEMESTER 5/PCD (Image Processing)/Plat Nomor2/runs/detect/train/weights/best.pt")

# Path folder input dan output
input_folder = "C:/SEMESTER 5/PCD (Image Processing)/Plat Nomor2/train/images"
output_folder = "C:/SEMESTER 5/PCD (Image Processing)/Plat Nomor2/train/results"

# Pastikan folder output ada
os.makedirs(output_folder, exist_ok=True)

# Nama kelas sesuai data.yaml
class_names = ['Bajaj', 'Bus', 'Mobil', 'Motor', 'Truk', 'Plat']

# Membuat DataFrame untuk hasil
columns = ['Image', 'Class', 'Confidence', 'X_min', 'Y_min', 'X_max', 'Y_max']
df = pd.DataFrame(columns=columns)

# Iterasi setiap file dalam folder input
for filename in os.listdir(input_folder):
    if filename.endswith(".jpg") or filename.endswith(".png"):  # Tambahkan format gambar lain jika perlu
        try:
            image_path = os.path.join(input_folder, filename)
            image = cv2.imread(image_path)

            if image is None:
                raise ValueError(f"Gambar {filename} tidak dapat dimuat.")

            # Inference dengan YOLO
            results = model(image_path)
            xyxy = results[0].boxes.xyxy.cpu().numpy()  # Koordinat bounding box
            conf = results[0].boxes.conf.cpu().numpy()  # Confidence score
            cls = results[0].boxes.cls.cpu().numpy()    # Class indices

            # Gambar bounding box pada gambar
            for box, confidence, class_id in zip(xyxy, conf, cls):
                x_min, y_min, x_max, y_max = map(int, box)  # Konversi ke integer
                label = f"{class_names[int(class_id)]}: {confidence:.2f}"  # Gunakan nama kelas dari data.yaml
                # Gambar kotak
                cv2.rectangle(image, (x_min, y_min), (x_max, y_max), (0, 255, 0), 2)
                # Tambahkan teks label
                cv2.putText(image, label, (x_min, y_min - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)

                # Simpan hasil ke DataFrame menggunakan pd.concat
                new_row = pd.DataFrame([{
                    'Image': filename,
                    'Class': class_names[int(class_id)],
                    'Confidence': confidence,
                    'X_min': x_min,
                    'Y_min': y_min,
                    'X_max': x_max,
                    'Y_max': y_max
                }])
                df = pd.concat([df, new_row], ignore_index=True)

            # Simpan gambar hasil ke folder output
            output_path = os.path.join(output_folder, filename)
            cv2.imwrite(output_path, image)

            print(f"Hasil deteksi disimpan di: {output_path}")
        
        except Exception as e:
            print(f"Terjadi error pada file {filename}: {e}")

# Simpan DataFrame ke file Excel
excel_output_path = os.path.join(output_folder, 'bounding_boxes.xlsx')
df.to_excel(excel_output_path, index=False)

print(f"Semua hasil bounding box telah disimpan di: {excel_output_path}")




image 1/1 C:\SEMESTER 5\PCD (Image Processing)\Plat Nomor2\train\images\012TFN_IDN_220113012101_20240619135349974_X921Y521W33H13_Motorcycle_Audi_unknown_058_03_01252_jpg.rf.3de122885fc46aee03d3e5c69f400f84.jpg: 384x640 1 Mobil, 4 Motors, 1 plat, 241.5ms
Speed: 8.0ms preprocess, 241.5ms inference, 10.5ms postprocess per image at shape (1, 3, 384, 640)
Hasil deteksi disimpan di: C:/SEMESTER 5/PCD (Image Processing)/Plat Nomor2/train/results\012TFN_IDN_220113012101_20240619135349974_X921Y521W33H13_Motorcycle_Audi_unknown_058_03_01252_jpg.rf.3de122885fc46aee03d3e5c69f400f84.jpg



C:\Users\isaia\AppData\Local\Temp\ipykernel_21116\3921645342.py:58: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, new_row], ignore_index=True)


image 1/1 C:\SEMESTER 5\PCD (Image Processing)\Plat Nomor2\train\images\0UPW_AUS_220313032101_20240619094952243_X1025Y610W42H16_Motorcycle_Audi_unknown_072_02_03288_jpg.rf.bc1d46be561a781b3ea737e40c450092.jpg: 384x640 2 Motors, 2 plats, 112.9ms
Speed: 5.0ms preprocess, 112.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)
Hasil deteksi disimpan di: C:/SEMESTER 5/PCD (Image Processing)/Plat Nomor2/train/results\0UPW_AUS_220313032101_20240619094952243_X1025Y610W42H16_Motorcycle_Audi_unknown_072_02_03288_jpg.rf.bc1d46be561a781b3ea737e40c450092.jpg

image 1/1 C:\SEMESTER 5\PCD (Image Processing)\Plat Nomor2\train\images\0_AUS_220113012101_20240619134048079_X0Y0W0H0_Motorcycle_Audi_unknown_010_02_09347_jpg.rf.c8c760796333d3b6071c2be57a12bb71.jpg: 384x640 1 Motor, 113.3ms
Speed: 2.0ms preprocess, 113.3ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)
Hasil deteksi disimpan di: C:/SEMESTER 5/PCD (Image Processing)/Plat Nomor2/train/results\0_AUS_2201130121

In [31]:
import pandas as pd

# Load data JSON
json_path = "detections.json"
with open(json_path, "r") as f:
    data = json.load(f)

# Konversi ke DataFrame
df = pd.DataFrame(data)

# Simpan ke file Excel
excel_path = "detections.xlsx"
df.to_excel(excel_path, index=False)

print(f"Data deteksi telah disimpan ke {excel_path}")


Data deteksi telah disimpan ke detections.xlsx


## Deteksi Plat Nomer menggunakan EASYOCR

In [10]:
import easyocr
reader = easyocr.Reader(['id'])

Progress: |██████████████████████████████████████████████████| 100.0% Complete

INFO:easyocr.easyocr:Download complete.


In [15]:
result = reader.readtext('C:/SEMESTER 5/PCD (Image Processing)/Plat Nomor/crop3.png',detail=0)
print(result)

['Pve', '4', '74', 'GJ04', '05']
